import type { RecursoInicial, CategoriaSlug } from '@/lib/inicial/types'

// Recursos con URL oficial verificada por búsqueda web el 14/09/2026.
// Matemática y juegos y Herramientas para docentes quedan sin recursos
// todavía: el documento de origen no nombra recursos concretos para esas
// categorías y no corresponde inventarlos.
const VERIFIED = '2026-09-14'

export const recursosIniciales: RecursoInicial[] = [
  // Recursos oficiales
  {
    id: 'continuemos-estudiando-inicial',
    title: 'Continuemos Estudiando · Educación Inicial',
    description:
      'Portal oficial de la DGCyE con propuestas, documentos y materiales para acompañar la enseñanza en el Nivel Inicial de la Provincia de Buenos Aires.',
    category: 'recursos-oficiales',
    type: 'Colección',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Multidisciplinar'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://continuemosestudiando.abc.gob.ar/inicial/',
    provider: 'Provincia de Buenos Aires',
    official: true,
    featured: true,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['PBA', 'DGCyE', 'Continuemos Estudiando'],
  },
  {
    id: 'diseno-curricular-inicial',
    title: 'Diseño Curricular para la Educación Inicial',
    description:
      'Documento curricular oficial vigente de la Provincia de Buenos Aires para el Nivel Inicial, con sus distintas versiones y ciclos.',
    category: 'recursos-oficiales',
    type: 'Documento',
    levels: ['Docentes'],
    areas: ['Multidisciplinar'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://abc.gob.ar/secretarias/areas/subsecretaria-de-educacion/educacion-inicial/educacion-inicial/disenos-curriculares-inicial',
    provider: 'Provincia de Buenos Aires',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Diseño curricular', 'PBA'],
  },
  {
    id: 'canto-rodado',
    title: 'Canto Rodado',
    description:
      'Serie de audiovisuales de la Dirección Provincial de Educación Inicial que acompaña y enmarca la tarea educativa de la primera infancia.',
    category: 'recursos-oficiales',
    type: 'Video',
    levels: ['Docentes'],
    areas: ['Formación docente'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://abc.gob.ar/secretarias/areas/subsecretaria-de-educacion/educacion-inicial/educacion-inicial/canto-rodado',
    provider: 'Provincia de Buenos Aires',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['PBA', 'Primera infancia'],
  },
  {
    id: 'esi-en-el-jardin',
    title: 'La ESI en el Nivel Inicial: apuntes para pensar los jardines',
    description:
      'Material de la DGCyE sobre Educación Sexual Integral como derecho, para el trabajo áulico y con la comunidad en el jardín.',
    category: 'recursos-oficiales',
    type: 'Documento',
    levels: ['Docentes'],
    areas: ['ESI'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://continuemosestudiando.abc.gob.ar/contenido/la-esi-en-el-nivel-inicial-apuntes-para-pensar-los-jardines/',
    provider: 'Provincia de Buenos Aires',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['ESI', 'PBA'],
  },

  // Educación Digital
  {
    id: 'aprender-conectados-inicial',
    title: 'Aprender Conectados · Nivel Inicial',
    description:
      'Materiales y propuestas del programa nacional de educación digital, programación y robótica, seleccionados para Nivel Inicial.',
    category: 'educacion-digital',
    type: 'Colección',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Educación digital'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.argentina.gob.ar/educacion/aprender-conectados/material-pedagogico/recursos-inicial',
    provider: 'Nación',
    official: true,
    featured: true,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Aprender Conectados', 'Educación digital'],
  },
  {
    id: 'digiaventuras',
    title: 'Digiaventuras · Guía para familias',
    description:
      'Serie educativa de Aprender Conectados pensada para Nivel Inicial, con guía para trabajar ciudadanía digital en familia.',
    category: 'educacion-digital',
    type: 'Video',
    levels: ['Sala 4', 'Sala 5'],
    areas: ['Ciudadanía digital'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/150283/digiaventuras-guia-',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Digiaventuras', 'Ciudadanía digital'],
  },

  // Pensamiento Computacional, Programación y Robótica
  {
    id: 'scratchjr',
    title: 'ScratchJr',
    description:
      'Entorno de programación visual diseñado para niños pequeños. Permite crear historias y juegos mediante bloques.',
    category: 'pensamiento-computacional',
    type: 'App',
    levels: ['Sala 5'],
    areas: ['Programación', 'Pensamiento computacional'],
    platforms: ['Tablet'],
    pricing: 'Gratuito',
    url: 'https://www.scratchjr.org/',
    provider: 'Institución educativa',
    official: false,
    featured: true,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Programación', 'Secuencias', 'Algoritmos', 'Creatividad'],
  },
  {
    id: 'pilas-bloques',
    title: 'Pilas Bloques',
    description:
      'Aplicación argentina para aprender a programar por bloques, con desafíos de dificultad creciente. Desarrollada por Program.AR (Fundación Sadosky).',
    category: 'pensamiento-computacional',
    type: 'App',
    levels: ['Sala 5'],
    areas: ['Programación', 'Pensamiento computacional'],
    platforms: ['Web', 'Tablet', 'Computadora'],
    pricing: 'Gratuito',
    url: 'https://pilasbloques.program.ar/',
    provider: 'Nación',
    official: true,
    featured: true,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Programación', 'Algoritmos', 'Program.AR'],
  },

  // Literatura y cuentos
  {
    id: 'educar-recursos',
    title: 'Educ.ar · Recursos',
    description:
      'Buscador de recursos educativos del portal nacional Educ.ar, con colecciones de cuentos, materiales y propuestas para Nivel Inicial.',
    category: 'literatura-y-cuentos',
    type: 'Colección',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Literatura'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos',
    provider: 'Nación',
    official: true,
    featured: true,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Cuentos', 'Educ.ar'],
  },
  {
    id: 'biblioteca-nacional-de-maestros',
    title: 'Biblioteca Nacional de Maestros',
    description:
      'Biblioteca digital con más de 40.000 recursos en línea: libros, cuentos, colecciones y material especializado en educación.',
    category: 'literatura-y-cuentos',
    type: 'Colección',
    levels: ['Docentes'],
    areas: ['Literatura'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://bnm.educacion.gob.ar/',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Biblioteca digital', 'BNM'],
  },

  // Arte y creatividad
  {
    id: 'tux-paint',
    title: 'Tux Paint',
    description:
      'Programa de dibujo libre y gratuito pensado especialmente para niñas y niños, con herramientas simples e íconos grandes.',
    category: 'arte-y-creatividad',
    type: 'Software',
    levels: ['Sala 3', 'Sala 4', 'Sala 5'],
    areas: ['Arte'],
    platforms: ['Computadora'],
    pricing: 'Gratuito',
    url: 'https://tuxpaint.org/',
    provider: 'Otro',
    official: false,
    featured: true,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Dibujo', 'Uso directo por niños y niñas'],
  },
  {
    id: 'canva-educacion',
    title: 'Canva Educación',
    description:
      'Herramienta de diseño para que docentes creen material didáctico, láminas y recursos visuales para el aula.',
    category: 'arte-y-creatividad',
    type: 'Software',
    levels: ['Docentes'],
    areas: ['Arte', 'Material didáctico'],
    platforms: ['Web'],
    pricing: 'Freemium',
    url: 'https://www.canva.com/es_ar/educacion/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Para docentes', 'Diseño'],
  },
  {
    id: 'genially',
    title: 'Genially',
    description:
      'Herramienta para que docentes creen presentaciones, imágenes interactivas y recursos didácticos animados.',
    category: 'arte-y-creatividad',
    type: 'Software',
    levels: ['Docentes'],
    areas: ['Material didáctico'],
    platforms: ['Web'],
    pricing: 'Freemium',
    url: 'https://genially.com/es/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Para docentes', 'Interactivo'],
  },

  // Música y sonido
  {
    id: 'chrome-music-lab',
    title: 'Chrome Music Lab',
    description:
      'Experimentos simples y visuales para explorar cómo funciona la música: ritmo, melodía, sonido. Ideal para primer contacto.',
    category: 'musica-y-sonido',
    type: 'Juego',
    levels: ['Sala 4', 'Sala 5'],
    areas: ['Exploración', 'Creación'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://musiclab.chromeexperiments.com/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Exploración sonora', 'Google'],
  },
  {
    id: 'incredibox',
    title: 'Incredibox',
    description:
      'Creación musical arrastrando íconos de sonido sobre personajes animados, para armar mezclas de forma lúdica.',
    category: 'musica-y-sonido',
    type: 'Juego',
    levels: ['Sala 5'],
    areas: ['Creación', 'Composición'],
    platforms: ['Web', 'Tablet'],
    pricing: 'Freemium',
    url: 'https://www.incredibox.com/es/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Composición', 'Ritmo'],
  },

  // Exploración del ambiente
  {
    id: 'google-earth-educacion',
    title: 'Google Earth · Educación',
    description:
      'Explorá el planeta en 3D: biomas, ciudades, paisajes. Propuestas y recursos para llevar el mundo al aula.',
    category: 'exploracion-del-ambiente',
    type: 'Sitio web',
    levels: ['Sala 5', 'Docentes'],
    areas: ['Ambiente natural y social'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.google.com/intl/es-419_ALL/earth/education/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Geografía', 'Exploración'],
  },
  {
    id: 'google-arts-and-culture',
    title: 'Google Arts & Culture',
    description:
      'Recorridos virtuales por museos y colecciones culturales de todo el mundo, en alta resolución.',
    category: 'exploracion-del-ambiente',
    type: 'Sitio web',
    levels: ['Docentes'],
    areas: ['Ambiente natural y social', 'Arte'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://artsandculture.google.com/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    status: 'active',
    tags: ['Museos', 'Cultura'],
  },

  // Matemática y juegos
  {
    id: 'ambiente-matematico-facilitador',
    title: 'Ambiente matemático facilitador en el Nivel Inicial',
    description:
      '¿Cómo construir un espacio para promover aprendizajes con contenidos matemáticos? Recurso interactivo con herramientas para trabajar estos contenidos en el aula.',
    category: 'matematica-y-juegos',
    type: 'Interactivo',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Matemática'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/159060/ambiente-matematico-facilitador-en-el-nivel-inicial',
    provider: 'Nación',
    official: true,
    featured: true,
    verifiedAt: '2026-09-14',
    status: 'active',
    tags: ['Números', 'Ambiente alfabetizador'],
  },
  {
    id: 'numeros-en-juego',
    title: 'Números en juego',
    description: 'Propuestas de juegos con contenidos de matemática para niños de Nivel Inicial.',
    category: 'matematica-y-juegos',
    type: 'Libro electrónico',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Matemática'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/91016/numeros-en-juego',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    status: 'active',
    tags: ['Juego matemático', 'Números'],
  },
  {
    id: 'juegos-de-tablero-nivel-inicial',
    title: 'Juegos de tablero en el Nivel Inicial',
    description:
      'Los juegos de mesa como oportunidad para construir ideas y reflexionar sobre contenidos numéricos, con orientaciones didácticas para las intervenciones docentes.',
    category: 'matematica-y-juegos',
    type: 'Libro electrónico',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Matemática'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/159061/juegos-de-tablero-en-el-nivel-incial',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    status: 'active',
    tags: ['Juego de mesa', 'Números'],
  },
  {
    id: 'mas-recursos-matematica-educar',
    title: 'Más recursos de Matemática · Educ.ar',
    description:
      'Buscador de Educ.ar filtrado por Nivel Inicial y Matemática, para seguir explorando más allá de esta selección curada.',
    category: 'matematica-y-juegos',
    type: 'Colección',
    levels: ['Docentes'],
    areas: ['Matemática'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/buscador?levels=1&subjects=24',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    status: 'active',
    tags: ['Buscador', 'Educ.ar'],
  },

  // Herramientas y formación docente
  {
    id: 'educar-alfabetizacion',
    title: 'Educ.ar · Alfabetización',
    description:
      'Ambiente educativo digital con propuestas de lectura y escritura para docentes de Nivel Inicial y primer ciclo, herramientas para diseñar clases y sugerencias de uso de IA.',
    category: 'herramientas-docentes',
    type: 'Sitio web',
    levels: ['Docentes'],
    areas: ['Formación docente'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/alfabetizacion',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    status: 'active',
    tags: ['Alfabetización', 'Planificación'],
  },
  {
    id: 'recursos-educativos-abiertos',
    title: 'Recursos Educativos Abiertos · 2da edición',
    description:
      'Recorrido por las bases del movimiento de Recursos Educativos Abiertos y los procesos de producción profesional y docente de materiales digitales.',
    category: 'herramientas-docentes',
    type: 'Libro electrónico',
    levels: ['Docentes'],
    areas: ['Formación docente', 'Producción de materiales'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/158229/segunda-edicion-recursos-educativos-abiertos-conceptos-herra',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    status: 'active',
    tags: ['REA', 'Producción de materiales'],
  },
  {
    id: 'microcursos-educar',
    title: 'Microcursos · Educ.ar',
    description:
      'Colección de microcursos autoasistidos y gratuitos para aprender a usar herramientas de Google, Quizizz, JClic, Genially y otras aplicaciones para producir materiales digitales.',
    category: 'herramientas-docentes',
    type: 'Colección',
    levels: ['Docentes'],
    areas: ['Formación docente', 'Producción de materiales'],
    platforms: ['Web'],
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/157318/microcursos',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    status: 'active',
    tags: ['Google', 'Quizizz', 'JClic', 'Microcurso'],
  },
]

export function getRecursosPorCategoria(slug: CategoriaSlug) {
  return recursosIniciales.filter((r) => r.category === slug && r.status === 'active')
}

export function getRecursosDestacados() {
  return recursosIniciales.filter((r) => r.featured && r.status === 'active')
}

export function contarRecursosPorCategoria(slug: CategoriaSlug) {
  return recursosIniciales.filter((r) => r.category === slug && r.status === 'active').length
}

