import type { RecursoInicial, CategoriaSlug } from '@/lib/inicial/types'

// Recursos con URL oficial verificada por búsqueda web el 14/09/2026.
// Metadatos curriculares (áreasCurriculares/approaches/computationalConcepts)
// agregados el 16/09/2026 en base al Diseño Curricular para la Educación
// Inicial (DGCyE, 2022) y las Líneas prioritarias para la Educación Digital
// 2025-2027 (DTE). Donde la relación curricular no es clara, el campo queda
// vacío a propósito: no se inventan asociaciones.
const VERIFIED = '2026-09-14'

export const recursosIniciales: RecursoInicial[] = [
  // Recursos oficiales
  {
    id: 'continuemos-estudiando-inicial',
    title: 'Continuemos Estudiando · Educación Inicial',
    description:
      'Portal oficial de la DGCyE con propuestas, documentos y materiales para acompañar la enseñanza en el Nivel Inicial de la Provincia de Buenos Aires.',
    category: 'recursos-oficiales',
    type: 'Colección',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Multidisciplinar'],
    approaches: [],
    pedagogicalUses: [
      'Encontrar propuestas de enseñanza ya elaboradas para Nivel Inicial.',
      'Bajar documentos y materiales oficiales de la Provincia.',
      'Explorar contenidos organizados por sala y por área.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://continuemosestudiando.abc.gob.ar/inicial/',
    provider: 'Provincia de Buenos Aires',
    official: true,
    featured: true,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['PBA', 'DGCyE', 'Continuemos Estudiando'],
  },
  {
    id: 'diseno-curricular-inicial',
    title: 'Diseño Curricular para la Educación Inicial',
    description:
      'Documento curricular oficial vigente de la Provincia de Buenos Aires para el Nivel Inicial, con sus distintas versiones y ciclos.',
    category: 'recursos-oficiales',
    type: 'Documento',
    levels: ['Docentes'],
    areas: ['Multidisciplinar'],
    areasCurriculares: [
      'Formación personal y social',
      'Prácticas del lenguaje',
      'Matemática',
      'Ambiente social y natural',
      'Juego',
      'Educación Artística',
      'Educación Física',
      'Educación Digital',
    ],
    approaches: [],
    pedagogicalUses: [
      'Consultar los propósitos y contenidos oficiales de cada área.',
      'Fundamentar una planificación con el marco curricular vigente.',
      'Revisar los principios fundantes del Nivel Inicial bonaerense.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://abc.gob.ar/secretarias/areas/subsecretaria-de-educacion/educacion-inicial/educacion-inicial/disenos-curriculares-inicial',
    provider: 'Provincia de Buenos Aires',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Diseño curricular', 'PBA'],
  },
  {
    id: 'canto-rodado',
    title: 'Canto Rodado',
    description:
      'Serie de audiovisuales de la Dirección Provincial de Educación Inicial que acompaña y enmarca la tarea educativa de la primera infancia.',
    category: 'recursos-oficiales',
    type: 'Video',
    levels: ['Docentes'],
    areas: ['Formación docente'],
    approaches: [],
    pedagogicalUses: [
      'Enmarcar pedagógicamente la tarea con la primera infancia.',
      'Compartir los videos en instancias de formación institucional.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://abc.gob.ar/secretarias/areas/subsecretaria-de-educacion/educacion-inicial/educacion-inicial/canto-rodado',
    provider: 'Provincia de Buenos Aires',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['PBA', 'Primera infancia'],
  },
  {
    id: 'esi-en-el-jardin',
    title: 'La ESI en el Nivel Inicial: apuntes para pensar los jardines',
    description:
      'Material de la DGCyE sobre Educación Sexual Integral como derecho, para el trabajo áulico y con la comunidad en el jardín.',
    category: 'recursos-oficiales',
    type: 'Documento',
    levels: ['Docentes'],
    areas: ['ESI'],
    areasCurriculares: ['Formación personal y social'],
    approaches: ['ESI'],
    pedagogicalUses: [
      'Fundamentar el abordaje de la ESI como derecho en el jardín.',
      'Planificar propuestas de ESI con la comunidad educativa.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://continuemosestudiando.abc.gob.ar/contenido/la-esi-en-el-nivel-inicial-apuntes-para-pensar-los-jardines/',
    provider: 'Provincia de Buenos Aires',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['ESI', 'PBA'],
  },

  // Educación Digital
  {
    id: 'aprender-conectados-inicial',
    title: 'Aprender Conectados · Nivel Inicial',
    description:
      'Materiales y propuestas del programa nacional de educación digital, programación y robótica, seleccionados para Nivel Inicial.',
    category: 'educacion-digital',
    type: 'Colección',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Educación digital'],
    areasCurriculares: ['Educación Digital'],
    approaches: ['Educación Digital'],
    pedagogicalUses: [
      'Sumar actividades de educación digital ya diseñadas para Inicial.',
      'Encontrar materiales para trabajar con tablets en la sala.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Tablet', 'Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.argentina.gob.ar/educacion/aprender-conectados/material-pedagogico/recursos-inicial',
    provider: 'Nación',
    official: true,
    featured: true,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Aprender Conectados', 'Educación digital'],
  },
  {
    id: 'digiaventuras',
    title: 'Digiaventuras · Guía para familias',
    description:
      'Serie educativa de Aprender Conectados pensada para Nivel Inicial, con guía para trabajar ciudadanía digital en familia.',
    category: 'educacion-digital',
    type: 'Video',
    levels: ['Sala 4', 'Sala 5'],
    areas: ['Ciudadanía digital'],
    areasCurriculares: ['Educación Digital'],
    approaches: ['Ciudadanía digital', 'Educación Digital'],
    pedagogicalUses: [
      'Trabajar ciudadanía digital con las familias.',
      'Disparar una conversación sobre cuidado en internet.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/150283/digiaventuras-guia-',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Digiaventuras', 'Ciudadanía digital'],
  },

  // Pensamiento Computacional, Programación y Robótica
  {
    id: 'scratchjr',
    title: 'ScratchJr',
    description:
      'Entorno de programación visual diseñado para niños pequeños. Permite crear historias y juegos mediante bloques.',
    category: 'pensamiento-computacional',
    type: 'App',
    levels: ['Sala 5'],
    areas: ['Programación', 'Pensamiento computacional'],
    areasCurriculares: ['Educación Digital'],
    approaches: ['Programación', 'Pensamiento computacional', 'Ciencias de la Computación'],
    computationalConcepts: ['Secuencias', 'Algoritmos', 'Programación'],
    pedagogicalUses: [
      'Crear historias animadas armando secuencias de bloques.',
      'Introducir la idea de instrucción y orden de los pasos.',
      'Producir una animación propia como cierre de una secuencia.',
    ],
    platforms: ['Tablet'],
    modality: 'Digital',
    devices: ['Tablet'],
    connectivity: 'Funciona sin internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: true,
    pricing: 'Gratuito',
    url: 'https://www.scratchjr.org/',
    provider: 'Institución educativa',
    official: false,
    featured: true,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Programación', 'Secuencias', 'Algoritmos', 'Creatividad'],
  },
  {
    id: 'pilas-bloques',
    title: 'Pilas Bloques',
    description:
      'Aplicación argentina para aprender a programar por bloques, con desafíos de dificultad creciente. Desarrollada por Program.AR (Fundación Sadosky).',
    category: 'pensamiento-computacional',
    type: 'App',
    levels: ['Sala 5'],
    areas: ['Programación', 'Pensamiento computacional'],
    areasCurriculares: ['Educación Digital'],
    approaches: ['Programación', 'Pensamiento computacional', 'Ciencias de la Computación'],
    computationalConcepts: ['Secuencias', 'Algoritmos', 'Resolución de problemas', 'Programación'],
    pedagogicalUses: [
      'Resolver desafíos de programación por bloques con dificultad creciente.',
      'Practicar la lógica de secuencias paso a paso.',
    ],
    platforms: ['Web', 'Tablet', 'Computadora'],
    modality: 'Digital',
    devices: ['Tablet', 'PC', 'Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://pilasbloques.program.ar/',
    provider: 'Nación',
    official: true,
    featured: true,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Programación', 'Algoritmos', 'Program.AR'],
  },

  // Literatura y cuentos
  {
    id: 'educar-recursos',
    title: 'Educ.ar · Recursos',
    description:
      'Buscador de recursos educativos del portal nacional Educ.ar, con colecciones de cuentos, materiales y propuestas para Nivel Inicial.',
    category: 'literatura-y-cuentos',
    type: 'Colección',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Literatura'],
    areasCurriculares: ['Prácticas del lenguaje'],
    lenguajesArtisticos: ['Literatura'],
    approaches: [],
    pedagogicalUses: [
      'Buscar cuentos y materiales de lectura para la sala.',
      'Sumar propuestas de lectura ya elaboradas por Educ.ar.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos',
    provider: 'Nación',
    official: true,
    featured: true,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Cuentos', 'Educ.ar'],
  },
  {
    id: 'biblioteca-nacional-de-maestros',
    title: 'Biblioteca Nacional de Maestros',
    description:
      'Biblioteca digital con más de 40.000 recursos en línea: libros, cuentos, colecciones y material especializado en educación.',
    category: 'literatura-y-cuentos',
    type: 'Colección',
    levels: ['Docentes'],
    areas: ['Literatura'],
    areasCurriculares: ['Prácticas del lenguaje'],
    lenguajesArtisticos: ['Literatura'],
    approaches: [],
    pedagogicalUses: [
      'Buscar libros y cuentos digitalizados para leer con el grupo.',
      'Acceder a material especializado en educación para planificar.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://bnm.educacion.gob.ar/',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Biblioteca digital', 'BNM'],
  },

  // Arte y creatividad
  {
    id: 'tux-paint',
    title: 'Tux Paint',
    description:
      'Programa de dibujo libre y gratuito pensado especialmente para niñas y niños, con herramientas simples e íconos grandes.',
    category: 'arte-y-creatividad',
    type: 'Software',
    levels: ['Sala 3', 'Sala 4', 'Sala 5'],
    areas: ['Arte'],
    areasCurriculares: ['Educación Artística'],
    lenguajesArtisticos: ['Educación visual'],
    approaches: ['Creación y producción digital'],
    pedagogicalUses: [
      'Que cada niño o niña produzca un dibujo digital propio.',
      'Explorar herramientas simples de dibujo antes de otras apps.',
    ],
    platforms: ['Computadora'],
    modality: 'Digital',
    devices: ['PC', 'Notebook'],
    connectivity: 'Funciona sin internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: true,
    pricing: 'Gratuito',
    url: 'https://tuxpaint.org/',
    provider: 'Otro',
    official: false,
    featured: true,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Dibujo', 'Uso directo por niños y niñas'],
  },
  {
    id: 'canva-educacion',
    title: 'Canva Educación',
    description:
      'Herramienta de diseño para que docentes creen material didáctico, láminas y recursos visuales para el aula.',
    category: 'arte-y-creatividad',
    type: 'Software',
    levels: ['Docentes'],
    areas: ['Arte', 'Material didáctico'],
    lenguajesArtisticos: ['Educación visual'],
    approaches: ['Creación y producción digital'],
    pedagogicalUses: [
      'Diseñar láminas, carteles y material visual para la sala.',
      'Producir recursos gráficos para comunicar con las familias.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'Requiere cuenta',
    requiresInstallation: false,
    pricing: 'Freemium',
    url: 'https://www.canva.com/es_ar/educacion/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    privacyNotes: ['Requiere crear una cuenta para guardar los diseños.'],
    tags: ['Para docentes', 'Diseño'],
  },
  {
    id: 'genially',
    title: 'Genially',
    description:
      'Herramienta para que docentes creen presentaciones, imágenes interactivas y recursos didácticos animados.',
    category: 'arte-y-creatividad',
    type: 'Software',
    levels: ['Docentes'],
    areas: ['Material didáctico'],
    approaches: ['Creación y producción digital'],
    pedagogicalUses: [
      'Crear presentaciones e imágenes interactivas para la sala.',
      'Armar recursos didácticos animados sin programar.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'Requiere cuenta',
    requiresInstallation: false,
    pricing: 'Freemium',
    url: 'https://genially.com/es/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    privacyNotes: ['Requiere crear una cuenta para guardar los diseños creados.'],
    tags: ['Para docentes', 'Interactivo'],
  },

  // Música y sonido
  {
    id: 'chrome-music-lab',
    title: 'Chrome Music Lab',
    description:
      'Experimentos simples y visuales para explorar cómo funciona la música: ritmo, melodía, sonido. Ideal para primer contacto.',
    category: 'musica-y-sonido',
    type: 'Juego',
    levels: ['Sala 4', 'Sala 5'],
    areas: ['Exploración', 'Creación'],
    areasCurriculares: ['Educación Artística'],
    lenguajesArtisticos: ['Música'],
    approaches: [],
    pedagogicalUses: [
      'Explorar de forma visual conceptos de ritmo y melodía.',
      'Experimentar con sonido sin necesidad de saber música.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://musiclab.chromeexperiments.com/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Exploración sonora', 'Google'],
  },
  {
    id: 'incredibox',
    title: 'Incredibox',
    description:
      'Creación musical arrastrando íconos de sonido sobre personajes animados, para armar mezclas de forma lúdica.',
    category: 'musica-y-sonido',
    type: 'Juego',
    levels: ['Sala 5'],
    areas: ['Creación', 'Composición'],
    areasCurriculares: ['Educación Artística'],
    lenguajesArtisticos: ['Música'],
    approaches: ['Creación y producción digital'],
    pedagogicalUses: [
      'Crear una mezcla musical propia arrastrando sonidos.',
      'Explorar capas y combinaciones de ritmo de forma lúdica.',
    ],
    platforms: ['Web', 'Tablet'],
    modality: 'Digital',
    devices: ['Tablet', 'Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Freemium',
    url: 'https://www.incredibox.com/es/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Composición', 'Ritmo'],
  },

  // Exploración del ambiente
  {
    id: 'google-earth-educacion',
    title: 'Google Earth · Educación',
    description:
      'Explorá el planeta en 3D: biomas, ciudades, paisajes. Propuestas y recursos para llevar el mundo al aula.',
    category: 'exploracion-del-ambiente',
    type: 'Sitio web',
    levels: ['Sala 5', 'Docentes'],
    areas: ['Ambiente natural y social'],
    areasCurriculares: ['Ambiente social y natural'],
    approaches: [],
    pedagogicalUses: [
      'Observar y comparar paisajes y biomas del mundo.',
      'Ubicar geográficamente un tema trabajado en la sala.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.google.com/intl/es-419_ALL/earth/education/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Geografía', 'Exploración'],
  },
  {
    id: 'google-arts-and-culture',
    title: 'Google Arts & Culture',
    description:
      'Recorridos virtuales por museos y colecciones culturales de todo el mundo, en alta resolución.',
    category: 'exploracion-del-ambiente',
    type: 'Sitio web',
    levels: ['Docentes'],
    areas: ['Ambiente natural y social', 'Arte'],
    areasCurriculares: ['Ambiente social y natural', 'Educación Artística'],
    lenguajesArtisticos: ['Educación visual'],
    approaches: [],
    pedagogicalUses: [
      'Hacer un recorrido virtual por un museo con el grupo.',
      'Mostrar obras de arte en alta resolución para observar y conversar.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://artsandculture.google.com/',
    provider: 'Otro',
    official: false,
    featured: false,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Museos', 'Cultura'],
  },

  // Matemática y juegos
  {
    id: 'ambiente-matematico-facilitador',
    title: 'Ambiente matemático facilitador en el Nivel Inicial',
    description:
      '¿Cómo construir un espacio para promover aprendizajes con contenidos matemáticos? Recurso interactivo con herramientas para trabajar estos contenidos en el aula.',
    category: 'matematica-y-juegos',
    type: 'Interactivo',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Matemática'],
    areasCurriculares: ['Matemática'],
    approaches: [],
    pedagogicalUses: [
      'Organizar un ambiente alfabetizador matemático en la sala.',
      'Encontrar herramientas concretas para trabajar contenidos numéricos.',
    ],
    platforms: ['Web'],
    modality: 'Mixta',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/159060/ambiente-matematico-facilitador-en-el-nivel-inicial',
    provider: 'Nación',
    official: true,
    featured: true,
    verifiedAt: VERIFIED,
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Números', 'Ambiente alfabetizador'],
  },
  {
    id: 'numeros-en-juego',
    title: 'Números en juego',
    description: 'Propuestas de juegos con contenidos de matemática para niños de Nivel Inicial.',
    category: 'matematica-y-juegos',
    type: 'Libro electrónico',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Matemática'],
    areasCurriculares: ['Matemática', 'Juego'],
    approaches: [],
    pedagogicalUses: [
      'Sumar propuestas de juegos con contenido matemático.',
      'Planificar secuencias de juego con intencionalidad numérica.',
    ],
    platforms: ['Web'],
    modality: 'Mixta',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/91016/numeros-en-juego',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Juego matemático', 'Números'],
  },
  {
    id: 'juegos-de-tablero-nivel-inicial',
    title: 'Juegos de tablero en el Nivel Inicial',
    description:
      'Los juegos de mesa como oportunidad para construir ideas y reflexionar sobre contenidos numéricos, con orientaciones didácticas para las intervenciones docentes.',
    category: 'matematica-y-juegos',
    type: 'Libro electrónico',
    levels: ['Sala 2', 'Sala 3', 'Sala 4', 'Sala 5', 'Docentes'],
    areas: ['Matemática'],
    areasCurriculares: ['Matemática', 'Juego'],
    approaches: [],
    computationalConcepts: ['Resolución de problemas'],
    pedagogicalUses: [
      'Usar juegos de mesa para trabajar contenidos numéricos.',
      'Reflexionar sobre cómo intervenir como docente durante el juego.',
    ],
    platforms: ['Web'],
    modality: 'Mixta',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/159061/juegos-de-tablero-en-el-nivel-incial',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Juego de mesa', 'Números'],
  },
  {
    id: 'mas-recursos-matematica-educar',
    title: 'Más recursos de Matemática · Educ.ar',
    description:
      'Buscador de Educ.ar filtrado por Nivel Inicial y Matemática, para seguir explorando más allá de esta selección curada.',
    category: 'matematica-y-juegos',
    type: 'Colección',
    levels: ['Docentes'],
    areas: ['Matemática'],
    areasCurriculares: ['Matemática'],
    approaches: [],
    pedagogicalUses: ['Seguir buscando materiales de matemática más allá de esta selección.'],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/buscador?levels=1&subjects=24',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Buscador', 'Educ.ar'],
  },

  // Herramientas y formación docente
  {
    id: 'educar-alfabetizacion',
    title: 'Educ.ar · Alfabetización',
    description:
      'Ambiente educativo digital con propuestas de lectura y escritura para docentes de Nivel Inicial y primer ciclo, herramientas para diseñar clases y sugerencias de uso de IA.',
    category: 'herramientas-docentes',
    type: 'Sitio web',
    levels: ['Docentes'],
    areas: ['Formación docente'],
    areasCurriculares: ['Prácticas del lenguaje'],
    approaches: ['Educación Digital'],
    pedagogicalUses: [
      'Planificar secuencias de lectura y escritura con apoyo digital.',
      'Conocer sugerencias de uso de IA para diseñar clases.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/alfabetizacion',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Alfabetización', 'Planificación'],
  },
  {
    id: 'recursos-educativos-abiertos',
    title: 'Recursos Educativos Abiertos · 2da edición',
    description:
      'Recorrido por las bases del movimiento de Recursos Educativos Abiertos y los procesos de producción profesional y docente de materiales digitales.',
    category: 'herramientas-docentes',
    type: 'Libro electrónico',
    levels: ['Docentes'],
    areas: ['Formación docente', 'Producción de materiales'],
    approaches: ['Educación Digital', 'Creación y producción digital'],
    pedagogicalUses: [
      'Conocer el marco conceptual de los Recursos Educativos Abiertos.',
      'Fundamentar la producción propia de materiales digitales.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresAccount: 'No requiere cuenta',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/158229/segunda-edicion-recursos-educativos-abiertos-conceptos-herra',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['REA', 'Producción de materiales'],
  },
  {
    id: 'microcursos-educar',
    title: 'Microcursos · Educ.ar',
    description:
      'Colección de microcursos autoasistidos y gratuitos para aprender a usar herramientas de Google, Quizizz, JClic, Genially y otras aplicaciones para producir materiales digitales.',
    category: 'herramientas-docentes',
    type: 'Colección',
    levels: ['Docentes'],
    areas: ['Formación docente', 'Producción de materiales'],
    approaches: ['Educación Digital', 'Creación y producción digital'],
    pedagogicalUses: [
      'Aprender a usar herramientas digitales para producir materiales.',
      'Capacitarse de forma autoasistida y a demanda.',
    ],
    platforms: ['Web'],
    modality: 'Digital',
    devices: ['Cualquier navegador'],
    connectivity: 'Requiere internet',
    requiresInstallation: false,
    pricing: 'Gratuito',
    url: 'https://www.educ.ar/recursos/157318/microcursos',
    provider: 'Nación',
    official: true,
    featured: false,
    verifiedAt: '2026-09-14',
    verificationStatus: 'Activo',
    status: 'active',
    tags: ['Google', 'Quizizz', 'JClic', 'Microcurso'],
  },
]

export function getRecursosPorCategoria(slug: CategoriaSlug) {
  return recursosIniciales.filter((r) => r.category === slug && r.status === 'active')
}

export function getRecursosDestacados() {
  return recursosIniciales.filter((r) => r.featured && r.status === 'active')
}

export function contarRecursosPorCategoria(slug: CategoriaSlug) {
  return recursosIniciales.filter((r) => r.category === slug && r.status === 'active').length
}

export function getRecursoPorSlug(slug: string) {
  return recursosIniciales.find((r) => (r.slug ?? r.id) === slug && r.status === 'active')
}
